### ISSUE TITLE
Làm thế nào để vẽ hình một cách rõ ràng?

### ISSUE THREAD

**Issue by Duong305** [Duong305/SE05-Nhom2#3]

**Comment by FixMeGuy** [comment]
Bọn mình sẽ làm cho các tấm đó tách ra 1 khoảng nhất định bằng cách thực hiện việc tịnh tiến giá trị x hoặc y hoặc z của các toạ độ điểm từng tấm

**Comment by Duong305** [comment]
Mình đã thấy chiếc tủ của các bạn nhưng làm sao để mình có thể thấy các thành phần tức từng tấm của tủ đó rõ ràng

**Comment by Duong305** [comment]
Vậy thì chính xác là bạn làm thế nào có thể nói rõ hơn cho mình ko ví dụ về cái tủ này

**Comment by FixMeGuy** [comment]
Bọn mình sẽ làm cho các tấm đó tách ra 1 khoảng nhất định bằng cách thực hiện việc tịnh tiến giá trị x hoặc y hoặc z của các toạ độ điểm từng tấm

**Comment by FixMeGuy** [comment]
Mình sẽ giữ nguyên các tấm song song rồi thay đổi các giá trị x hoặc y hoặc z của các tọa độ điểm từng tấm bằng cách thêm hoặc bớt từng giá trị x,y,z đó sao cho nó cách đủ xa để có thể nhìn rõ từng tấm cảm ơn bạn về câu hỏi

**Comment by Duong305** [comment]
Vậy thì chính xác là bạn làm thế nào có thể nói rõ hơn cho mình ko ví dụ về cái tủ này

**Comment by FixMeGuy** [comment]
Mình sẽ giữ nguyên các tấm song song rồi thay đổi các giá trị x hoặc y hoặc z của các tọa độ điểm từng tấm bằng cách thêm hoặc bớt từng giá trị x,y,z đó sao cho nó cách đủ xa để có thể nhìn rõ từng tấm cảm ơn bạn về câu hỏi

**Comment by Duong305** [comment]
Vậy thì làm thế nào để xoay các tấm vì việc giữ nguyên vị trí như thế mình không thể xem kĩ được các kích thước khác của các tấm

**Comment by FixMeGuy** [comment]
Mình sẽ dùng thuật toán xoay hình bằng các công thức lượng giác vì mỗi tấm đều được vẽ dựa trên các trục toạ độ x,y,z ví dụ:
muốn xoay tấm đó quay quanh trục y thì được giá trị mới của các x và các z của mỗi toạ độ điểm là x' = x*cosθ + z*sinθ, z' = x*sinθ - z*cosθ
muốn xoay tấm đó quay quanh trục x thì được giá trị mới của các y và các z của mỗi toạ độ điểm là y' = y*cosθ - z*sinθ, z' = y*sinθ + z*cosθ
muốn xoay tấm đó quay quanh trục z thì được giá trị mới của các x và các y của mỗi toạ độ điểm là x' = x*cosθ - y*sinθ, y' = x*sinθ + y*cosθ trong đó θ là số góc cần quay

**Comment by Duong305** [comment]
cảm ơn bạn về thuật toán hay
