### ISSUE TITLE
Làm thế nào để vẽ đường cong bằng ezdxf?

### ISSUE THREAD

**Issue by Duong305** [Duong305/SE05-Nhom2#4]

**Comment by Duong305** [comment]
Mình đã thấy các bạn vẽ các tấm hình hộp chữ nhật đó bằng ezdxf của python vậy còn về đường cong thi sao ezdxf đâu có hàm nào có sẵn để vẽ đường cong?

**Comment by FixMeGuy** [comment]
Mình sẽ áp dụng phương trình bezier
![image](https://user-images.githubusercontent.com/73946407/104838915-7566d180-58f0-11eb-95ff-869ec3e05617.png)
để tính ra các toạ độ điểm có quỹ đạo trở thành đường cong rồi chỉ việc nối các đoạn thẳng cực nhỏ đó lại với nhau tức nối 2 cặp điểm 1 bằng phương thức add_line() của ezdxf

**Comment by Duong305** [comment]
Vậy là bạn sẽ vẽ các đường cong 1 cách tổng quát vì mình thấy file bạn không có số liệu cụ thể của toạ độ điểm điều khiển?

**Comment by FixMeGuy** [comment]
Đúng vậy file mình làm ra sẽ vẽ được tất cả mọi đường cong mà đầu vào cung cấp kể cả có thay đổi như thế nào đi nữa

**Comment by Duong305** [comment]
cảm ơn bạn
